### ISSUE TITLE
Poor list formatting

### ISSUE THREAD

**Issue by mindplay-dk** [oltmannsdaniel/skeleton-plus#1]
Bullet-points and numbers in `<ol>` or `<ul>` tags do not align vertically.

![image](https://cloud.githubusercontent.com/assets/103348/13488987/a7951cb4-e124-11e5-89c1-4b090b2a167b.png)

This also has the unfortunate effect of breaking `contenteditable` - I've seen this go wrong already in two different editors. Looks like this:

![image](https://cloud.githubusercontent.com/assets/103348/13489045/fccf7486-e124-11e5-93be-c4818efc3807.png)

Typical list formatting looks more like this:

![image](https://cloud.githubusercontent.com/assets/103348/13489094/4a9667a6-e125-11e5-9abc-85e555380f36.png)

I don't know if it was deliberately designed this way, but it's unorthodox and not generally considered good typography, as far as I'm aware.

**Comment by mindplay-dk** [comment]
Also, there's a barely noticeable change in font-size on nested lists - this is poor typography as well, it will cause the vertical grid rhythm to break up when lists display side-by-side in a grid.

I'm going to submit a PR to address these issues.

**Comment by mindplay-dk** [comment]
Uhm, wow, I guess I thought this would be a quick fix, but looks like a can of worms - vertical grid is completely messed-up. Looks like the original Skeleton completely ignores the issue of vertical grid as well.

This is not a "fix", it's going to take a lot of work to remedy this.

I'm sorry, I don't have enough time to invest in this right now - I'd like to, when time allows, but I have too many other projects right now.

**Comment by ghost** [comment]
I will solve this problems as fast as I can. But mometly I have no much time because I must learn for the school (I am only 15) so would you like to help me?

**Comment by patrickblackjr** [comment]
I'll help when possible.

**Comment by ghost** [comment]
Thanks

**Comment by Mortiferr** [comment]
I'm not sure skeleton was the best framework to build off of...Skeleton was poorly designed.

**Comment by Mortiferr** [comment]
https://github.com/skeleton-framework/skeleton-framework

I would suggest maybe merging your contributions to this fork of it...they have npm and everything already set up. I appreciate your effort but this one is already more popular.

**Comment by ghost** [comment]
This Project is just a simple option and a simple alternative to the original Skeleton Version. It is also for new Developers in CSS that would like to work on a simple project. So thanks for the tip but that is not an option for me.

**Comment by patrickblackjr** [comment]
That is perfectly understandable. That was me with JavaScript not too long ago.

**Comment by ghost** [comment]
@mindplay-dk
`contenteditable` is now fixed. But not in the Version 2.0.0. But in 2.0.1 I will fix the List formatting from `ol` and `ul` , also  `contenteditable`

**Comment by ghost** [comment]
@mindplay-dk I will fix this in the new Version. A restart. New Font-sizes, Bug fixes, etc. (v0.0.1)
