### ISSUE TITLE
multiple column/s pluralization issue

### ISSUE THREAD

**Issue by MrJadaml** [oltmannsdaniel/skeleton-plus#17]
component-a.js

```
<div className="row">
  <div className="one column">◀︎</div>
  <Card />
  <div className="one column">▶︎</div>
</div>
```

component-b.js

```
<div className="card ten columns">
  ... stuff
</div>
```

The following sets the first "◀︎ div" on its own row, above the rest of the content.

```
-----------------------------
|◀︎                          |
-----------------------------
|         ...stuff      | ▶︎ |
-----------------------------
```

If I change the **first** `one-column` class to the not proper pluralization of `one-columns` it works as expected with the "◀︎ div" falling in along side the card element. 

component-a.js

```
<div className="row">
  <div className="one columns">◀︎</div>
  <Card />
  <div className="one column">▶︎</div>
</div>
```

```
-----------------------------
|◀︎ |    ...stuff        | ▶︎ |
-----------------------------
```

It also works if both are in the plural of `one-columns`

**Comment by ghost** [comment]
@MrJadaml You could do a pull request on that if you want.

(Sorry for that late answer)

**Comment by ghost** [comment]
@MrJadaml I found some mistakes I did with the Grid, I will redesign the Grid completely.

**Comment by ghost** [comment]
Fixed now. Sorry that it took so long.
