### ISSUE TITLE
Dropdown on exempel site?

### ISSUE THREAD

**Issue by RimuJim** [oltmannsdaniel/skeleton-plus#2]
Just wondering: is the link "dropdown example+" supposed to do something? Looking at it just now on iOS it's not clickable.

**Comment by ghost** [comment]
@RimuJim On all my Devices tge Dropdown is working. I can not check this for IOS. Maybe you can made a few Tests when I do a commit. Or start a Pull Request.

Thanks.

**Comment by ghost** [comment]
But on my Devices it works so I close this now.
