### ISSUE TITLE
IMPORTANT - Anyone interested in working on here

### ISSUE THREAD

**Issue by ghost** [oltmannsdaniel/skeleton-plus#21]
Hey guys,

Thank you for your support. Currently I am 15-years-old and cannot work on this Project anymore, because I started two different big Projects that I want run as a Business.

I hope you understand what I say now: If anyone is interested in having this Project, ask me per mail (daniel@thedcdesigns.com) and feel free to add stuff.

Best regards
Daniel Oltmanns

**Comment by 1fabiopereira** [comment]
OK nice !! 😄
