### ISSUE TITLE
Professional CDN : JSDelivr

### ISSUE THREAD

**Issue by smartclash** [oltmannsdaniel/skeleton-plus#24]
Why not opt for JSDelivr CDN. Just go into their docs site and get to know how to add this project into their site. That's it. You will have your project in the world's biggest open source CDN provider

**Comment by ghost** [comment]
You could do a new pull-request on that. @smartclash

**Comment by ghost** [comment]
Sorry for the late response, but I saw we Can not meet the requirements as you can see here: https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library

**Comment by smartclash** [comment]
@oltmannsdaniel Well, it's only for CDNJS. I said about the JSDelivr

**Comment by ghost** [comment]
@smartclash Ok, could you do it, because for me it will take more than 2 weeks to find some free time.

**Comment by smartclash** [comment]
@oltmannsdaniel Sure, I could. But I am not the owner or a person with push access to this repo :(

**Comment by ghost** [comment]
@smartclash Just open s pull request. I will always take a look on new pull requests.

**Comment by smartclash** [comment]
@oltmannsdaniel Well, just read the docs. There is no use of any push access. In fact, there is no work in our side (like adding .yml files etc.). I will take care of that. You be happy with your work :wink:

**Comment by smartclash** [comment]
@oltmannsdaniel Check this, I've submitted your project. Now, it's on their hands whether to approve project or not. Anyways, best of luck to you

https://github.com/jsdelivr/jsdelivr/pull/17891

**Comment by ghost** [comment]
@smartclash As you can see we had been accepted by JSDelivr. Thanks for your work 👍 :1st_place_medal:
