### ISSUE TITLE
A new version

### ISSUE THREAD

**Issue by ghost** [oltmannsdaniel/skeleton-plus#25]
So I am thinking of changing some stuff. Maybe some better Tooltips and a much better font, as well as some color updates.

So the Todo List is as following:
- [x]  A new font (Roboto/Rubik/Roboto Mono/..)
- [x] Some minor fixes
- [x] Color Updates
- [x] New Components
    - [x] Pagination
    - [x] Progress bars
    - [x] Cards
- [x] New Tooltips
- [x] Rename some classes
- [x] Finally roll out a complete new Version of Skeleton (Cause if the huge changes,  I think we need to move from v2 to v3)

What are your thoughts? Any suggestions for changes?

**Comment by nanotime** [comment]
I like the project but it can have more elements like `area` and `card`, with a lot of variables 😄 

I think i can work on it and then send a PR, but right now i have no time 😞 

Anyway, i like the ideas btw.

**Comment by ghost** [comment]
@nanotime Ok. Maybe you could wxplain your ideas in more details. And I have no time currently as well, but in about 3 weeks I can work on this here again.

**Comment by nanotime** [comment]
Ok, sorry for the delay.

Well, skeleton plus is nice but it lacks of some css components that will be useful, like:

- [Cards](https://v4-alpha.getbootstrap.com/components/card/)
- [Pagination (only styles).](https://v4-alpha.getbootstrap.com/components/pagination/)
- [Progress Bars](https://v4-alpha.getbootstrap.com/components/progress/).
- [Input groups](https://v4-alpha.getbootstrap.com/components/input-group/)
- [Buttons groups](https://v4-alpha.getbootstrap.com/components/button-group/).
- [Badges](https://v4-alpha.getbootstrap.com/components/badge/).
- [List group](https://v4-alpha.getbootstrap.com/components/list-group/).

I would rely on the css components of bootstrap or we can dig into other bigger frameworks and get some of their components/ideas.

One of this examples is the bootstrap 4 cards, they are a super flexible UI component, widely used in the actual design, why not get them in skeleton plus?

Also, why not change the grid to a flexbox grid? There is an abandoned project called [flexbox-grid](https://github.com/kristoferjoseph/flexboxgrid), open source that we can take an implement inside skeleton plus.

The idea remains the same, pure css elements, no JS. It's a lot of work, and i'm not a hyper-expert but i can help to make this tool even more cool, step by step.

Hope to be useful... Cheers!🍻

**Comment by ghost** [comment]
Cool ideas. But I wouldn't move to flexbox yet, because I want to support older browsers. Maybe we can add an extra class for flexbox.

I can join working on that in about 1.5 weeks (aftet the 15th of May). Cheers 🍻 @nanotime

**Comment by stevebobdob** [comment]
Could you add flexbox (and maybe grid) using @supports?

**Comment by ghost** [comment]
@stevebobdob You mean a libary like modernizr?

**Comment by stevebobdob** [comment]
No, more like this https://hacks.mozilla.org/2016/08/using-feature-queries-in-css/

so you would have standard skeleton, then a @supports flexbox with flexbox css, then possible a @supports grid section with grid css. would need some resets in each.

**Comment by nanotime** [comment]
Hmm sounds pretty good @stevebobdob ... it's easy to use the "normal" code as a fallback and get the flexbox things with`@support`.

Grid is cool, but i don't understand (yet) the specification so, i can't talk about it (yet) 🤓.

**Comment by atomi** [comment]
stackable grid would be nice

**Comment by ghost** [comment]
@atomi So you mean a grid in another grid element right?

**Comment by atomi** [comment]
Stackable so that the right columns drop below the left columns for mobile screens.

**Comment by ghost** [comment]
Shall we rename some stuff, to explain it a bit better by class name?

**Comment by nanotime** [comment]
@oltmannsdaniel like what? I think that we need to make a plan, with everything we need like rewrites, renames, new components and so on.

**Comment by ghost** [comment]
@nanotime Will open a new Branch for the Version and everyone can make a pull request to the `IDEAS`file

**Comment by ghost** [comment]
**[AT]everyone** [Use this file](https://github.com/oltmannsdaniel/skeleton-plus/blob/v3.0/IDEAS.md) to have a overview of all the  things that will be added. If you want to add something, just **open a new Pull Request** and say, why we should add it and what it is.

So if you want to stay up-to-date, just `Watch` this project.

**Comment by ghost** [comment]
#27 We need to remake the whole Grid System. But let's keep flexbox in seperated classes.

**Comment by DPUK44** [comment]
I agree. Let's keep flexbox separated due to older browsers.

I loved Skeleton and I am loving what you are doing to the project, keeping it 'alive'.

Appreciate ya!

**Comment by ghost** [comment]
@DPUK44 I recently moved to a new GitHub Account @oldaniel. And I started `wire-css`. So maybe I will move skeleton-plus.... Maybe.... 

**Tell me your opinions if I should go on and rebuild the whole oroject in a better smaller more attractive version.**

**Comment by alexandermccormick** [comment]
Better, smaller, AND more attractive? I would like that. I used this in most of my projects, instead of the ever encumbering bootstrap. Slowly I'm converting people haha.

I really like the CSS animations as opposed to having to add another js file too. Thanks for everything, and keep up the good work.

**Comment by ghost** [comment]
@nanotime @stevebobdob @alexandermccormick @DPUK44 @atomi 

So we need to work out a plan how I rebuild stuff. Currently, `wire-css` ([here](https://github.com/oldaniel/wire-css)) is my new framework. As this `skeleton-plus` has an size of wapping 18kb I want to reduce it. Everyone ok with a full rewrite? The classes and naming stuff will be the same.

**Comment by stevebobdob** [comment]
Sounds good to me.

**Comment by alexandermccormick** [comment]
I'm down. Shoot me an email if you need any help with anything. I'm still working on a few skills, but I'm a fast learner.

**Comment by ghost** [comment]
@alexandermccormick Keep an eye on the issues. I will now prepare a new setup for rewriting in v3 branch

**Comment by alexandermccormick** [comment]
Will do, thanks.

**Comment by nanotime** [comment]
Not a bad idea, i think. Rename classes, do the repetitive work with SASS loops and so on. But yes, indeed, we need a plan and reactivate the project. I have been working a lot with react and bootstrap and I would like to work on skeleton for next projects.

**Comment by DPUK44** [comment]
@oldaniel that sounds good to me to. I love using frameworks to build WP themes and I loved how simple Sleleton is.

Looking forward to seeing what you come up with man.

**Comment by nanotime** [comment]
Just let us know when the change is going to be done, and then we can re discuss the roadmap, features, and so on.

**Comment by ghost** [comment]
@nanotime The work can start today, I have a lot of free time in the next 2 weeks because I haven't any school lessons cause of Vacation.

**Comment by DPUK44** [comment]
Let me know if there is anything I can do to help out. I don't have massive amounts of time but I can offer some!

**Comment by nanotime** [comment]
Well I'm on Mexico right now and I was in the earthquake, still fixing the office and the whole city but have some sparks of free time, so, let's do it.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/30154375/30978563-335d54e4-a47b-11e7-863c-7f2439bf59ec.png)
So this is the current typography guys of the new version. @DPUK44 @nanotime

**Comment by nanotime** [comment]
Let's begin for the very basic: the structure. (BTW i love those typography ❤️).

Talking about of structure, i found some "issues"... things like buttons (just for one mention) are pretty static. One thing that i love from frameworks is the "mixinized" structure, it brings a lot of customization, we can re-work some components to be mixins and set the defaults as a classes that instance those mixins and, if the user want a new type of button he/she can just grab the mixin and instance it in a new class.

A beautiful potential of skeleton-plus is exactly that, it's simple but can be customizable because is just CSS.

But these are just ideas, what do you want to do?

**Comment by ghost** [comment]
@nanotime So I want to take my `wire-css` as inspiration. But we will add a lot of more stuff to it.

The idea with the mixins is amazin, never thought about it, but I will do the basics now, and than we can talk in more detail about mixins.

BTW I use this font for months, and I love it too

So any other ideas we can implement?

**Comment by DPUK44** [comment]
I’ve not tried your wire-css but one main drawback with skeleton compared to bootstrap for example is lack of responsive nav. Would be nice to add multiple options for nav, e.g top, fixed, side pop out.

**Comment by alexandermccormick** [comment]
I always hesitate to use built in navs. Trying to get fancy with them can sometimes be a hassle.

Simple wire framed navbar could encourage more people to customize it more, rather than using the stock one. Look at the bootstrap navbar, everyone and their mother has the same exact thing haha

**Comment by nanotime** [comment]
@alexandermccormick indeed! navs are easy, i hate the over-complications... and with flexbox you can do a lot just with css. Please...

Bring some navs utils like vars for height, colors and items align will be enough, the hamburger button is overrated, you can hide the nav and show it with a "onClick" event.

About of what more to do? I posted here some new elements that i think are good ideas to implement (cards, etc). Just CSS items.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/30154375/31249729-b251cc2e-aa18-11e7-86a9-cb4f10be00e8.png)
Added some colors. Your opinions?

And here some tasks @DPUK44 @alexandermccormick @nanotime :
- Adding the old grid system, but optimize it (better class names, etc.)
- Adding some prototype navigations like slide out, etc.
- Adding a table system (a copy&paste from `wire-css` and translate it to `scss`)

**Comment by alexandermccormick** [comment]
I'll play around a bit with those Friday, I might focus more on the nav prototypes.

**Comment by DPUK44** [comment]
Like the colours and will look over the task list this weekend at some point

Sent from my iPhone

On 5 Oct 2017, at 21:04, Daniel Oltmanns <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://user-images.githubusercontent.com/30154375/31249729-b251cc2e-aa18-11e7-86a9-cb4f10be00e8.png>
Added some colors. Your opinions?

And here some tasks @DPUK44<https://github.com/dpuk44> @alexandermccormick<https://github.com/alexandermccormick> @nanotime<https://github.com/nanotime> :

  *   Adding the old grid system, but optimize it (better class names, etc.)
  *   Adding some prototype navigations like slide out, etc.
  *   Adding a table system (a copy&paste from wire-css and translate it to scss)

**Comment by alexandermccormick** [comment]
Sorry, multi-tasking. The colours do look good. I like them

**Comment by ghost** [comment]
For an better and faster communication:

https://gitter.im/skeleton-plus/v3

**Comment by ghost** [comment]
@nanotime @stevebobdob @DPUK44 It was now a long time I haven't done any changes..... So I decided just today to keep `v3` more like the current version but a bit more modern. So it will be more colorful and won't have a monospace font.

Opinions?

**Comment by nanotime** [comment]
Let me create a UI kit svg to express my ideas 👍

**Comment by ghost** [comment]
Ok cool, looking forward to take a look at it.

**Comment by ghost** [comment]
@nanotime @stevebobdob @DPUK44 So I made now a few changes and will now finish up the new `skeleton-plus` version. [The TODO list here](https://github.com/oldaniel/skeleton-plus/issues/25#discussion_bucket). Anything you want to add?

**Comment by nanotime** [comment]
Nope, nothing to add. I'm a little busy, that's why i cannot get involved in the last months.
