### ISSUE TITLE
Mobile responsiveness 

### ISSUE THREAD

**Issue by CLYeo** [oltmannsdaniel/skeleton-plus#27]
hi,

not sure if this is an issue or feature, extracted from the demo page.
I resize chrome till 100+ px and it is still showing 12 columns.
![image](https://user-images.githubusercontent.com/29327709/27045565-ddab91e2-4fd3-11e7-8c32-a8eb0213ae95.png)

shouldn't it will change from columns to rows as per the idea of responsive design from the original skeleton demo page
![image](https://user-images.githubusercontent.com/29327709/27045650-270c110e-4fd4-11e7-8328-4ed0c83097a7.png)

**Comment by ghost** [comment]
This is a small Issue from the Grid Class Naming. 

If I remember correctly use `-sm` prefix to keep the size on mobile devices, the `-md` for medium devices. If you use no prefixes, it will keep the size on any screen size.

**Comment by ghost** [comment]
Maybe we should do some renaming on there for the new version.

**Comment by CLYeo** [comment]
oh OK. I got it. 
maybe add a section about the normal grid column in the demo page will be good.
thanks

**Comment by CLYeo** [comment]
hi,

I was playing around the responsiveness in cssdesk.com and it seems like there is some issue with the 'columns' tag too

skeleton plus original before resizing
![image](https://user-images.githubusercontent.com/29327709/27075999-7e2fd832-505e-11e7-8e82-061a0f0c667e.png)


after 
![image](https://user-images.githubusercontent.com/29327709/27075961-5a5ba4ae-505e-11e7-9a4d-30192119bb17.png)


changed the CSS to the original skeleton
![image](https://user-images.githubusercontent.com/29327709/27076144-e386b82c-505e-11e7-9e3c-f7daab55b293.png)

this is the link to the CSSDesk i used to try skeleton plus
http://www.cssdesk.com/8Stgc

cheers

**Comment by ghost** [comment]
@CLYeo Thats cause of the remaking of the Gird System. This will be new and reinvented in the v3.0

**Comment by CLYeo** [comment]
ok sure.

i will soon contribute some ideas to the new version
